Closes #17 add a config validator helper function
pharmaverse/envsetup pull request #23
Opened 2023-02-11 18:37 UTC by nicholas-masel

**This covers paths validation.  Will add autos validation once autos branches merge into dev.**

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-02-11 23:46 UTC, mstackhouse requested changes

2023-02-11 23:46 UTC, mstackhouse commented on tests/testthat/test-utils.R
> +  expect_message(validate_config(config::get(file = path)),
@nicholas-masel  these tests are failing, and I think it's because of the highlighted text from `usethis::ui_field()`. I suggest using `expect_snapshot()` on the whole thing instead of checking each individual line. That'll be more robust. 

Actually - all of these unit tests should probably use snapshot testing because that will hold up better if the `usethis::ui_` functions update how they write output in the future.

2023-02-13 18:46 UTC, nicholas-masel commented on tests/testthat/test-utils.R
> +  expect_message(validate_config(config::get(file = path)),
Updated to snapshot tests.

2023-02-13 19:10 UTC, nicholas-masel commented
@mstackhouse Snapshot tests pass for 4.2 and release, but fail for 4.0.  I'm inclined to merge, since the message is what I expect.

There is one other fail due to library, but this is fixed already in another branch.

2023-02-14 12:56 UTC, merged

2023-02-14 12:57 UTC, mstackhouse reviewed
All good