Closes #20, #31 feature request decision needed for initial envsetup.yml
pharmaverse/envsetup pull request #33
Opened 2023-02-13 21:42 UTC by nicholas-masel

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-02-13 22:14 UTC, nicholas-masel commented
@mstackhouse Snapshot test fails on R4.0, but passes on 4.1 and release.  4.1 and release have one fail but that is fixed in your PR.    I believe the checks are fine as is and can be merged if you agree w/the code/implementation.

2023-02-13 22:42 UTC, nicholas-masel commented on R/init.R
> +    build_from_config(
Users should have the option to build the directories when they provide a custom configuration.  I'll adjust this code to provide this feature.

2023-02-14 11:30 UTC, nicholas-masel commented on R/init.R
> +    build_from_config(
Added this featur with https://github.com/pharmaverse/envsetup/pull/33/commits/eaa4315425509bda6f4349a19bcfb5decc58b9f7

2023-02-14 12:13 UTC, nicholas-masel commented
> @mstackhouse Snapshot test fails on R4.0, but passes on 4.1 and release. 4.1 and release have one fail but that is fixed in your PR. I believe the checks are fine as is and can be merged if you agree w/the code/implementation.

I found snapshot variants to cover this.
```r
r_version <- function() paste0("R", getRversion()[, 1:2])

test_that("can capture version nickname", {
  expect_snapshot(version$nickname, variant = r_version())
})
```
https://www.tidyverse.org/blog/2021/10/testthat-3-1/#snapshot-tests

The admiralci tests though use an old snapshot date for R4.0, where these variants are not available yet.  I've requested an update with admiral ci, https://github.com/pharmaverse/admiralci/issues/61.

I don't want to hold this PR back though due to this.

2023-02-14 12:47 UTC, mstackhouse commented
> @mstackhouse Snapshot test fails on R4.0, but passes on 4.1 and release. 4.1 and release have one fail but that is fixed in your PR. I believe the checks are fine as is and can be merged if you agree w/the code/implementation.

That's fine with the snapshot tests and part of the intent - since they change over time. you don't want to have to rewrite the messages constantly to maintain the tests

2023-02-14 12:55 UTC, mstackhouse requested changes
One small comment and then I'm good.

2023-02-14 12:55 UTC, mstackhouse commented on R/init.R
> +      missing_directories <- !sapply(paths, dir.exists)
So if you look at the docs for `sapply()` they indicate that it shouldn't be used in package development. Even though this is a controlled instance, I'd recommend that we replace this with vapply:
```suggestion
      missing_directories <- !vapply(paths, dir.exists, TRUE)
```

2023-02-15 14:35 UTC, merged