closes #70
pharmaverse/envsetup pull request #71
Opened 2024-12-30 16:44 UTC by nicholas-masel

Thank you for your Pull Request! Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the reference page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2025-01-06 20:30 UTC, mstackhouse requested changes

2025-01-06 20:30 UTC, mstackhouse commented on R/autos.R
> +  collated_func <- roxygen2:::generate_collate(path)
@nicholas-masel calling an internal of {roxygen} is a bit problematic. Is there an exported function we could use to do this instead? Not that we've been able to get this to CRAN in the first place, but this is another thing that would cause us a rejection.

2025-01-08 14:22 UTC, nicholas-masel commented on R/autos.R
> +  collated_func <- roxygen2:::generate_collate(path)
@mstackhouse I don't see anything exported here from roxygen2.   We could request them to export, bring this function into envsetup, or leave it as is.  I did this based on this discussion here, https://stat.ethz.ch/pipermail/r-devel/2013-August/067210.html.  I wasn't sure if this should be done in zzz.R though and then the function documented in a separate R script, similar to what was done in logrx for safely, https://github.com/search?q=repo%3Apharmaverse%2Flogrx%20run_safely%20&type=code.

What do you think?

2025-01-08 14:37 UTC, mstackhouse commented on R/autos.R
> +  collated_func <- roxygen2:::generate_collate(path)
Since we're not on CRAN let's just move forward with what you have, but let's submit an issue to request that they export the function given that we have a use case for it.

2025-01-08 14:37 UTC, mstackhouse approved these changes

2025-03-13 20:46 UTC, merged